---

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel

env:
  node: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0
